### ISSUE TITLE
css injection of .container breaking other sites layout

### ISSUE THREAD

**Issue by thordurk91** [nichite/squanchify#2]
beacause of a too general css rule in squanchyStyle.css affecting bootstraps defaults.

.container {
    padding-left: 10px;
    padding-right: 10px;
    width: 225px;
}

affected sites are fx. vimeo.com (bottom bar) and isb.is (bank site)

**Comment by nichite** [comment]
Good call! I normally take care to have specific css class names, but I had
figured that since this was its own popup the css wouldn't interfere with
the main page. I was mistaken.

Anyway, it's fixed and the new version has been published.

On Wed, Nov 4, 2015 at 9:54 PM, hundasupa notifications@github.com wrote:

> beacause of a too general css rule in squanchyStyle.css affecting
> bootstraps defaults.
> 
> .container {
> padding-left: 10px;
> padding-right: 10px;
> width: 225px;
> }
> 
> affected sites are fx. vimeo.com (bottom bar) and isb.is (bank site)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nichite/squanchify/issues/2.

## 

Nicolas Hite
Harvard College '14
McMaster-Carr Supply Company
nic.hite@mcmaster.com
